### ISSUE TITLE
Not Working On Ios Device

### ISSUE THREAD

**Issue by Bhavin004** [TheArchitect123/TitanSocket#1]
Its properly working on android device but not working in ios device

**Comment by TheArchitect123** [comment]
Make sure to set your iOS Transport security settings. iOS blocks any domains/endpoints that it does not trust.
Have you tried allowing arbitrary loads, or at least configured your allowed domains on the info.plist (on your app)?

Take a look at this.
https://stackoverflow.com/a/31807139

**Comment by Bhavin004** [comment]
I have tried these also but not able to connect with socket on ios app
can you please explain steps for implementing these library for multiplatform app

**Comment by TheArchitect123** [comment]
Hi Sorry for the long delay.
I've been crazy busy and allot has been going on.
If you try the latest version 0.2.7, it should work now for iOS.

I've replaced the Socket Engine for iOS, and it's working on a test client of mine, with ATS (Application Transport Security) Fully enabled.
